spring.application.name=service-workflow
server.port=8085

# ===============================
# Datasource (PostgreSQL - Camunda)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/camunda_db
spring.datasource.username=camunda
spring.datasource.password=Camunda123!
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# ===============================
# Camunda Configuration
# ===============================
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
#camunda.bpm.admin-user.firstName=Admin
#camunda.bpm.admin-user.lastName=User
#camunda.bpm.admin-user.email=admin@dksoft.com

camunda.bpm.filter.create=All tasks
camunda.bpm.webapp.enabled=true

camunda.bpm.database.schema-update=true
camunda.bpm.database.type=postgres

camunda.bpm.history-level=full
camunda.bpm.auto-deployment-enabled=true

# ===============================
# Microservices URLs
# ===============================
services.enrollment.url=http://localhost:8090
services.student.url=http://localhost:8089
services.department.url=http://localhost:8086
services.finance.url=http://localhost:8084
services.notification.url=http://localhost:8086

# ===============================
# Feign Configuration
# ===============================
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=BASIC

# ===============================
# Eureka (optional)
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Logging
# ===============================
logging.level.org.camunda=INFO
logging.level.com.dksoft=DEBUG


