package pfe.example.departementservice.enumerateur;

public enum StatutDemandeInscription {
    SOUMIS,
    EN_COURS_SCOLARITE,
    REJETE_SCOLARITE,
    EN_COURS_DEPARTEMENT,
    REJETE_DEPARTEMENT,
    EN_ATTENTE_DOCUMENT,
    DEPARTEMENT_VALIDE,
    EN_ATTENTE_PAIEMENT,
    SCOLARITE_VALIDEE,
    PAIEMENT_VALIDE,
    REJETE_FINANCE,
    INSCRIT,
    RELANCE,
    LISTE_ATTENTE,
}
