# Server Configuration
server.port=8085
server.servlet.context-path=/

# Application Name
spring.application.name=camunda-service

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/camunda_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Camunda Configuration
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.firstName=Admin
camunda.bpm.admin-user.lastName=User

# Auto-deployment of BPMN files
camunda.bpm.auto-deployment-enabled=true

# Database configuration
#camunda.bpm.database.schema-update=true
#camunda.bpm.database.type=mysql

# History level
#camunda.bpm.generic-properties.properties.history-level=full
camunda.bpm.history-level=FULL


# Authorization
camunda.bpm.authorization.enabled=true

# Filter
camunda.bpm.filter.create=All tasks

# Logging
logging.level.org.camunda=INFO
logging.level.org.springframework=INFO
logging.level.com.example.camunda=DEBUG