spring.application.name=etudiant-service
server.port=8089

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ===== OCR Configuration =====
ocr.tesseract.datapath=/usr/share/tesseract-ocr/4.00/tessdata
ocr.tesseract.languages=fra+ara+eng

# ===== AI / Ollama Configuration =====
ai.ollama.base-url=http://localhost:11434
ai.ollama.model=llama3.2


# ========== LOGGING CONFIGURATION ==========
logging.level.root=INFO
logging.level.pfe.example.etudiantservice=DEBUG
logging.level.com.github.sardine=DEBUG
logging.level.org.apache.http.wire=DEBUG

# Format des logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Fichier de logs (optionnel)
spring.config.import=optional:configserver:http://localhost:9999
#c'est a dire voire l'autre partie de la configuration




