spring.application.name=etudiant-service
server.port=8089

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.config.import=optional:configserver:http://localhost:9999
#c'est a dire voire l'autre partie de la configuration



