spring.application.name=config-service
server.port=9999
#spring.cloud.config.server.git.uri=file://D:/projerPfeDev/springBoot/moduleSuiviProcessusInscription/config-repo
spring.cloud.config.server.git.uri=https://github.com/chaymakharrat/config-app-pfe
spring.cloud.config.server.git.default-label=master
management.endpoints.web.exposure.include=health,refresh
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}