# Configuration pour que DevTools charge correctement Sardine
restart.include.sardine=/sardine-.*\\.jar
restart.include.httpclient=/httpclient-.*\\.jar
restart.include.httpcore=/httpcore-.*\\.jar
restart.include.commons-logging=/commons-logging-.*\\.jar
restart.include.slf4j=/slf4j-.*\\.jar